# GitHub Actions workflow to automatically process recurring tasks
#
# This workflow:
# 1. Runs every hour (or manually)
# 2. Processes recurring tasks in all files in the todos/ folder
# 3. If new tasks were created, opens a PR with the changes
#
# Setup:
# 1. Copy this file to .github/workflows/recurring.yml in your repo
# 2. Create a todos/ folder with your .txt files
# 3. In repo Settings > Actions > General, enable:
#    "Allow GitHub Actions to create and approve pull requests"

name: Process recurring tasks

on:
  # Run every hour at minute 0 (in UTC)
  schedule:
    - cron: '0 * * * *'
  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    # Required permissions for creating branches and PRs
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install todotxt CLI from GitHub
      - name: Install todotxt
        run: pip install git+https://github.com/msornay/todotxt.git

      # Run do-rec on each file in todos/ folder (ignoring subfolders)
      # Note: -o cannot be the same as input file, so we use a temp file
      - name: Process recurring tasks
        run: |
          for file in todos/*; do
            [ -f "$file" ] || continue
            echo "Processing $file"
            todotxt do-rec "$file" -o "$file.tmp" && mv "$file.tmp" "$file"
          done

      # Only create a PR if any files changed
      - name: Create PR if changed
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Exit early if no changes
          if git diff --quiet; then
            echo "No changes"
            exit 0
          fi

          # Create a unique branch name with timestamp
          branch="recurring-$(date +%Y%m%d-%H%M)"

          # Configure git for committing
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Create branch, commit, push, and open PR
          git checkout -b "$branch"
          git add todos/
          git commit -m "Process recurring tasks"
          git push -u origin "$branch"
          gh pr create --title "Recurring tasks update" --body "Auto-generated by recurring tasks workflow"
